global.WALL_HEALTH = 100000;
global.WALL_CRITICAL = 10000;
global.CONSIDER_SCOUTING_OLD = 5000;
global.AVOID = []
global.RESERVE_BODY = [
  MOVE,
  MOVE,
  MOVE,
  CLAIM,
  CLAIM
]

global.CONTROLLER_SIGN="Alpha Lima Papa Hotel Alpha"


global.UPGRADER_GOAL_MIN=100000;
global.UPGRADER_GOAL_MAX=200000;